#!/bin/sh
set -e

echo "[debug] PocketBase: $(/pb/pocketbase --version 2>&1 | head -1)"

# types.d.ts was generated by PocketBase JSVM — shows what functions exist in this version
echo "[debug] JSVM API (router-related):"
grep -i "router\|routeAdd\|routerAdd\|addRoute" /pb/pb_data/types.d.ts 2>&1 | head -40 || echo "types.d.ts not found"

echo "[debug] JSVM API (all declare function):"
grep "^declare function" /pb/pb_data/types.d.ts 2>&1 | head -40 || echo "types.d.ts not found"

mkdir -p /pb/pb_data/fresh

echo "[init] starting pocketbase --hooksDir=/pb/pb_hooks ..."
exec /pb/pocketbase serve --http=0.0.0.0:8090 --dir=/pb/pb_data/fresh --hooksDir=/pb/pb_hooks
